# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-25 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_profile_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileid',
            field=models.IntegerField(),
        ),
    ]
